language: rust
rust:
  - nightly
install:
  - cargo install grcov
script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Zno-landing-pads"
  - cargo bench --all
  - cargo test --all --verbose
  - |
    zip -0 ccov.zip `find . \( -name "twitchbot*.gc*" \) -print`;
    ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;
branches:
  only:
    - master
