language: rust
rust:
  - nightly
install:
  - cargo install grcov
script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Zno-landing-pads"
  - cargo build
  - cargo test --all
  - |
    zip -0 ccov.zip `find . \( -name "modelflat_bot*.gc*" \) -print`;
    grcov ccov.zip \
      --source-dir . \
      --output-type coveralls+ \
      --llvm --branch --ignore-not-existing \
      --ignore "/*"  \
      --output-file codecov.json \
      --token $CODECOV_TOKEN \
      --commit-sha "$(git rev-parse HEAD)";
    bash <(curl -s https://codecov.io/bash) -f codecov.json;
  # do bench last
  - cargo bench --all
branches:
  only:
    - master
