language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: stable
install:
  - cargo install grcov
  - cargo build --verbose
script:
  - cargo test --verbose --all
  - cargo bench --verbose --all
branches:
  only:
    - master
