language: rust
rust:
  - nightly
cache:
  - cargo
install:
  - cargo install grcov
script:
  - export PROJECT_NAME=bot
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Zno-landing-pads"
  - cargo clean
  - cargo build
  - cargo test --all
  - |
    zip -0 ccov.zip `find . \( -name "${PROJECT_NAME}*.gc*" \) -print`;
    grcov ccov.zip \
      --source-dir . \
      --output-type coveralls+ \
      --llvm --branch --ignore-not-existing \
      --ignore "/*"  \
      --ignore "app/*"  \
      --output-file codecov.json \
      --token $CODECOV_TOKEN \
      --commit-sha "$(git rev-parse HEAD)";
    bash <(curl -s https://codecov.io/bash) -f codecov.json;
  - cargo clean
  - |
    if [ -n "${TRAVIS_TAG}" ]; then
      echo "Deploying version: ${TRAVIS_TAG}"
      echo ${SSH_KEY} > ssh_key
      ssh -i ./ssh_key twitchbot@feelsdankman.com "./deploy.sh ${TRAVIS_TAG} ; exit"
      rm -P ssh_key
    else
      echo "No tag found, skipping deploy step..."
    fi
branches:
  only:
    - master
